### ISSUE TITLE
Make tqdm optional if manager is used as a python module.

### ISSUE THREAD

**Issue by rasjani** [MarketSquare/webdrivermanager#2]
If people use webdrivermanager as a python module, it would be nicer to let them decide if tqdm output can be disable in order to not mess up their console output.

Update: apparently i just didnt read the code carefully enough - it is a possibility already but there's a hard requirement for tqdm still present which is not nice from my perspective - might consider this to be pip install time extra feature ..

**Comment by DEADSEC-SECURITY** [comment]
In the downloaders you have the param show_progress_bar which should disable the progress bar.

Example:
`ChromeDriverManager().download_and_install(show_progress_bar=False)`
This won't show the progress bar from tqdm
