### ISSUE TITLE
Add possibility to probe browser version and match that into webdriver version that should be downloaded

### ISSUE THREAD

**Issue by rasjani** [MarketSquare/webdrivermanager#23]

**Comment by NMamm** [comment]
For each operating system we need to define a way to detect the installed version of a given browser. On windows, this involves reading the registry to identify the location of the executable. With the executable's path we can use pefile to do this on any os.

For each browser, we need to define a method for querying the matching driver version for a given browser version. download_and_install(version) will take over from there.

**Comment by xylix** [comment]
I propose using subprocess and `--version` argument for detecting browser versions. It is a bit ugly but it will work on all operating systems. https://github.com/rasjani/webdrivermanager/pull/43  contains an implementation for Chrome.
