### ISSUE TITLE
Add support for python 3.10

### ISSUE THREAD

**Issue by kishaningithub** [MarketSquare/webdrivermanager#80]
From the doc below i see that max version of python supported is 3.7

https://github.com/rasjani/webdrivermanager#status

Can support for python 3.10 be added i am asking because this is used widely especially by users of [robot framework](https://robotframework.org/) and they started supporting python 3.10

https://github.com/robotframework/robotframework/releases/tag/v4.1.1

I tried seeing the CI script to add python 3.10 to the test suite but it doesnt seem to contain the python versions

https://github.com/rasjani/webdrivermanager/blob/master/azure/job_template.yml

**Comment by DEADSEC-SECURITY** [comment]
I use python 3.11 and I dont have any issues. There are no constraints in the package Pypi so you should be able to use it on 3.7+

**Comment by kishaningithub** [comment]
Okie then.. closing this issue
