### ISSUE TITLE
if you don't set a log_level, an exception will be raised.

### ISSUE THREAD

**Issue by sander76** [MarketSquare/webdrivermanager#85]
The Drivermanager (for Edge) has a default `log_level = none`. This raises an attribute exception. If you set it to `log_level=logging.INFO` (or any other loglevel) all is fine.

**Comment by DEADSEC-SECURITY** [comment]
What version are you using?

**Comment by sander76** [comment]
Oef, that's a long time ago. I think I forgot to close this issue as I am happily using this for a long time already.
Let's close ?

**Comment by DEADSEC-SECURITY** [comment]
Go ahead and close it :)
